# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- learningstages

pool:
  vmImage: ubuntu-latest

stages:
- stage: BuildStage
  jobs:
   - job: Jobone
     steps:
      - script: echo Hello, world! Job1
        displayName: 'Run a one-line script'
   - job: Jobtwo
     steps:
      - script: echo Hello, world! Job2
        displayName: 'Run a one-line script'

