trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: BuildStage
  jobs:
   - job: Jobone
     steps:
      - bash: echo $(Build.BuildNumber)
      - bash: echo $(Agent.BuildDirectory)
      - bash: echo $(Agent.HomeDirectory)
      - bash: echo $(Agent.Name)
      - bash: echo $(Build.ContainerId)
      - bash: echo $(Build.SourceBranchName)
      - bash: echo $(Build.SourcesDirectory)
      - bash: echo $(System.DefaultWorkingDirectory)
      - bash: ls -R $(System.DefaultWorkingDirectory)
      - bash: echo $(Build.ArtifactStagingDirectory)
      - task: CopyFiles@2
        inputs:
          SourceFolder: 'System.DefaultWorkingDirectory'
          Contents: '**/*.yml'
          TargetFolder: 'Build.ArtifactStagingDirectory'



# - stage: CompileStage
#   dependsOn: BuildStage
#   jobs:
#    - job: compileJob3
#      steps:
#       - script: echo Hello, world! Job3
#         displayName: 'Run a one-line script'

# - stage: TestStage
#   dependsOn: BuildStage
#   jobs:
#    - job: TestJob4
#      steps:
#       - script: echo Hello, world! Job4
#         displayName: 'Run a one-line script'
        
# - stage: DeployStage
#   dependsOn: TestStage
#   jobs:
#    - job: deployJob5
#      steps:
#       - script: echo Hello, world! Job5
#         displayName: 'Run a one-line script'
